controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_cart_example:
    path: /api/cart/calculate-cart/
    controller: App\Controller\Api\CartApiController::calculateCart
    methods: [POST]
